sudo: required
dist: trusty

language: cpp

env:
  global:
    - PATH=$HOME/rez/bin/rez:$PATH
    - OVERRIDE_BOOST_MODULES="--with-python"
    - REZ_REPO_PAYLOAD_DIR="/tmp/REPO"
    - CACHE_NAME=REZ

cache:
  timeout: 1800
    directories:
      $HOME/rez/
      $HOME/packages/

jobs:
  include:
    - stage: precache
      cache:
        timeout: 1800
          directories:
            $HOME/rez/
            $HOME/packages/
      script: true
      before_install:
        - sudo apt-get -qq update
      install: # Make sure this doesn't run if found in cache
        - ls $HOME
        - ls $HOME/rez
        - ls $HOME/packages
        - bash .travis/precache_rez.sh
    - &build
      name: "Build Boost ${VERSION}"
      stage: build
      env: VERSION=1.70.0
      script:
        - mkdir -pv ${REZ_REPO_PAYLOAD_DIR}
        - echo "CREATED REZ_REPO_PAYLOAD_DIR ${REZ_REPO_PAYLOAD_DIR}"
        - BOOST_ARCHIVE_URL=http://downloads.sourceforge.net/project/boost/boost/${VERSION}/boost_$(echo ${VERSION} | tr "." "_").tar.gz
        - echo "BOOST ARCHIVE URL ${BOOST_ARCHIVE_URL}"
        - OLDPWD=$PWD
        - mkdir -p ${REZ_REPO_PAYLOAD_DIR}/boost
        - cd ${REZ_REPO_PAYLOAD_DIR}/boost
        - curl -LO $BOOST_ARCHIVE_URL
        - cd $OLDPWD
        - sed -i s/version.*=.*/version=\"${VERSION}\"/ package.py
        - rez-build -i
    - <<: *build
      env: VERSION=1.69.0
    - <<: *build
      env: VERSION=1.68.0
    - <<: *build
      env: VERSION=1.67.0
    - <<: *build
      env: VERSION=1.66.0
    - <<: *build
      env: VERSION=1.65.1
    - <<: *build
      env: VERSION=1.64.0
    - <<: *build
      env: VERSION=1.63.0
    - <<: *build
      env: VERSION=1.62.0
    - <<: *build
      env: VERSION=1.61.0
    - <<: *build
      env: VERSION=1.60.0
    - <<: *build
      env: VERSION=1.59.0
    - <<: *build
      env: VERSION=1.58.0
    - <<: *build
      env: VERSION=1.57.0
    - <<: *build
      env: VERSION=1.56.0
    - <<: *build
      env: VERSION=1.55.0