version: 2
jobs:
  build:
    working_directory: ~/build_dir
    docker:
      - image: "buildpack-deps:bionic"
    environment:
        - OVERRIDE_BOOST_MODULES=--with-python
        - REZ_REPO_PAYLOAD_DIR=/tmp/REPO
    steps:
      - run: echo 'export PATH=$HOME/rez/bin/rez:$PATH' >> $BASH_ENV
      - run: apt-get update && apt-get install -y cmake
      - checkout
      - restore_cache:
          key: -v2-rez-python
      - run: 'bash .circleci/precache_rez.sh'
      - save_cache:
          key: -v2-rez-python
          paths:
            - /root/rez
            - /root/packages
      - run:
          name: Build Boost 1.70.0
          command: 'BOOST_VERSION=1.70.0 bash .circleci/build_boost.sh'
      - run:
          name: Build Boost 1.65.1.0
          command: 'BOOST_VERSION=1.55.0 bash .circleci/build_boost.sh'
      - run:
          name: Build Boost 1.55.0
          command: 'BOOST_VERSION=1.55.0 bash .circleci/build_boost.sh'